name: API Linting with Redocly

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest
      - name: Run Lint tests
        run: redocly lint ./openapi/openapi.yaml --format=github-actions

